"""orders

Revision ID: 2f80bb9e26ae
Revises: 
Create Date: 2019-04-09 13:34:34.225243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f80bb9e26ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('order_status', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_order_date'), 'order', ['date'], unique=False)
    op.create_index(op.f('ix_order_name'), 'order', ['name'], unique=False)
    op.create_index(op.f('ix_order_order_status'), 'order', ['order_status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_name'), table_name='order')
    op.drop_index(op.f('ix_order_date'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
