"""Orders

Revision ID: 38bc0134452b
Revises: 2f80bb9e26ae
Create Date: 2019-04-22 11:36:27.398803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bc0134452b'
down_revision = '2f80bb9e26ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'numpacks',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    op.create_index(op.f('ix_orders_numpacks'), 'orders', ['numpacks'], unique=False)
    op.drop_column('orders', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_numpacks'), table_name='orders')
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.alter_column('orders', 'numpacks',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('orders', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
